### ISSUE TITLE
hi, how use in windows?

### ISSUE THREAD

**Issue by bairespm** [rse/closingcredits#1]
i download closingcredits 1.0.4 but dont work, its empty index.html.  i instal node and git but dont work. please help. thanks

**Comment by rse** [comment]
No, the original index.html is not empty. Perhaps your download is broken. Closely follow the steps under "Local Use" in the README and it will work.

**Comment by bairespm** [comment]
I only use Windows, could it be that you only explained it for Linux?

In Windows I can't get it to work. When I open the html it doesn't show anything... when I enter the code I see that it has code but it doesn't seem to work. That's why I ask you for help.

**Comment by rse** [comment]
I see, you are trying to open the file directly from the filesystem via a Browser, right? This doesn't work, as this context does not allow the script to load the closingcredits.txt file. You have to open the index.html via a "http"-URL and not a "file"-URL. As the README explains, the app is intended to be running inside OBS Studio or vMix. There such a problem does not exist. As a workaround you can run "npm start" after "npm install" and then open the URL http://127.0.0.1:9999/closingcredits/

**Comment by rse** [comment]
I've adding this information to the README now, too. Please check it again.
