### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by bairespm** [rse/closingcredits#2]
I only use Windows, could it be that you only explained it for Linux?

In Windows I can't get it to work. When I open the html it doesn't show anything... when I enter the code I see that it has code but it doesn't seem to work. That's why I ask you for help.

**Comment by rse** [comment]
Your problem is not related to Windows, but related to the fact that you are trying to open the file via "file"-URL instead of "http"-URL. Use the "npm start" command which is not given in the README as a workaround.

**Comment by bairespm** [comment]
I got it to work, outside of obs... with your npm start instructions but I want to use it in obs and there is no way I can do it. and I can't remotely modify the txt so unfortunately I won't be able to use it... your idea was very good. I will try to do something in HTML with Java that is similar. thanks all the same
